pool:
   vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
   imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

trigger:
- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'lcastro_azure_devops'
    artifact: 'node:8'
    project: 'lcastro_pipeline'
- main
